### ISSUE TITLE
Add aliasing error message

### ISSUE THREAD

**Issue by TheSeamau5** [evancz/error-message-catalog#1]
This code: 
```elm
type alias Vector2 = 
  { x : Float
  , y : Float
  }
  
v : Vector2
v = 
  { x = 0 }
```

triggers this error message:
```
Type mismatch between the following types on line 9, column 5 to 10:

       Temp32703.Vector2

       { x : Float }

   It is related to the following expression:

       { x = 0 }

```

The whole "temp" part is super weird and not beginner friendly

**Comment by evancz** [comment]
I understand this as "type error messages should localize types so they are easier to read" which I agree with.

I'll open an issue for this on the compiler to track progress. Thanks for the report!

**Comment by TheSeamau5** [comment]
Sorry about the terrible name. I couldn't come up with a clear enough name. I hope the body was clear enough.

I think you may want to consider the possibility of expanding on the alias type.
 
Like adding:

```
mismatch between Vector and { x = 0 } ... yadda yadda ...

where 

type alias Vector = 
  { x : Float
  , y : Float
  }
```

as a sort of reminder. I think it may helpful to just remind what the type alias aliases to save time on going hunting for docs and stuff. 

Ideally, someday, an IDE would offer a "go to definition" feature if you right-click or something, but in the meantime, this could help get that instant feedback and see actually what the mismatch is about.
