### ISSUE TITLE
@docs to undefined name gives long unhelpful error message

### ISSUE THREAD

**Issue by Apanatshka** [evancz/error-message-catalog#20]
The driving real-life example is [signal-extra 5.1.1](https://github.com/Apanatshka/elm-signal-extra/tree/5.1.1), which gives:

```
-- UNDEFINED DOCUMENTATION ------------------------------ ./src/Signal/Extra.elm

Your module documentation includes `filterMap` which is not exported.

 2|>{-| Utility functions that aren't in the `Signal` module from
 3|>`elm-lang/core`. 
 4|>
 5|># Flipped fancy map
 6|>@docs (~>)
 7|>
 8|># Zipping and unzipping
 9|>For those too lazy to write a record or union type.  
10|>@docs zip, zip3, zip4, unzip, unzip3, unzip4
11|>
12|># Stateful
13|>@docs foldp', foldps, foldps', runBuffer, runBuffer', delayRound
14|>
15|># Switching
16|>@docs switchWhen,switchSample
17|>
18|># Filters
19|>@docs keepIf,keepWhen,sampleWhen,keepThen,keepWhenI,filter,filterMap
20|>
21|># Combining
22|>@docs fairMerge, combine, mapMany, applyMany
23|>-}

Is it misspelled? Should it be exported?
```

The value `filterMap` was removed in a previous version along with the documentation and the export, but the name in the `@docs` was mistakenly left in. 

This message is too long, and the hints are not exactly describing the situation.

**Comment by Apanatshka** [comment]
Some possible improvements:

Minmise doc comment
----------------------------
Minimise the outputted doc comment to the line* with the `@docs` statement with the missing name and underline the missing name:

```
19| @docs keepIf,keepWhen,sampleWhen,keepThen,keepWhenI,filter,filterMap
                                                               ^^^^^^^^^
```

* Not sure if you're allowed to put the list of `@docs` names on multiple lines, if so only the line with the name needs to be displayed I think.. I'm not sure. How is this usually done with a faulty sub-expression?

Consider this a naming error
------------------------------------
Call this error `NAMING ERROR` or something like that instead of `UNDEFINED DOCUMENTATION`, at least in this case where the name is undefined. If it's defined but not exported, or defined and exported but doesn't have a doc comment, then those are different situations. 
Make suggestions "Maybe you want one of the following?" as is usual for a naming error.

**Comment by rtfeldman** [comment]
:+1: for not using the term `UNDEFINED` - many JS programmers who see that will reflexively think "oh, that means an `undefined` value leaked out into the string somehow;" my first thought upon seeing `UNDEFINED DOCUMENTATION` was "lol this program has a bug."

Maybe `MISSING DOCUMENTATION`?

**Comment by Apanatshka** [comment]
@rtfeldman I really think in this particular case it's best to handle this error as a plain old Naming Error (`NAMING ERROR` is the name the compiler uses for this). I was referring to a name that doesn't exist in the `@docs`.

**Comment by rtfeldman** [comment]
Got it. Makes sense to me! :+1:

**Comment by evancz** [comment]
I like both the recommendations! There is a special parser for comments that extracts everything, so I think you need to have it add regions to the docs (easy) and then thread that through the checking code somehow (not too crazy)

Would love help on this!

**Comment by Apanatshka** [comment]
I don't have the bandwidth in the coming weeks, but you could post a link to this issue on the mailing list? Sounds like something small and cool for someone with an interest in the compiler/compilers in general.

**Comment by evancz** [comment]
Was fixing another docs issue and figured this would just take a half hour. So here's the new message:

```
-- DOCUMENTATION ERROR ------------------------------------------------- ./src/List.elm

Your module documentation includes `isEmpty` which is not exported.

17| @docs isEmpty, length, reverse, member
          ^^^^^^^
Is it misspelled? Should it be exported?
```

**Comment by Apanatshka** [comment]
Much better!
What about the idea to consider it a name error and suggesting other names?

**Comment by evancz** [comment]
Happy to get a PR. It's harder to do, and I wonder if anyone would actually report that independent of the massive message?

**Comment by evancz** [comment]
Ah, it wasn't that hard.

```
-- DOCUMENTATION ERROR ------------------------------------------ ./src/List.elm

Your module documentation includes `issEmpty` which is not exported.

17| @docs issEmpty, length, reverse, member
          ^^^^^^^^
Is it misspelled? Should it be exported? Maybe you want one of the following?

    isEmpty

```

**Comment by Apanatshka** [comment]
perfect :smile:
