### ISSUE TITLE
REPL error message, trying to get type of Html.div

### ISSUE THREAD

**Issue by jessitron** [evancz/error-message-catalog#24]
$ elm repl
    Elm REPL 0.4.2 (Elm Platform 0.15.1)
      See usage examples at <https://github.com/elm-lang/elm-repl>
      Type :help for help, :exit to exit
    > import Html
    > Html.div
    ReferenceError: navigator is not defined

Maybe I can't do things with Html in the repl?

**Comment by evancz** [comment]
This is the same as https://github.com/elm-lang/elm-repl/issues/48 which is kind of a REPL issue, kind of a virtual-dom issue. I'm actually working on it today!

**Comment by evancz** [comment]
Okay, should be solved now. Described in more detail in the REPL issue. Thanks for the report!
