### ISSUE TITLE
Try to be more precise when type mismatches occur

### ISSUE THREAD

**Issue by TheSeamau5** [evancz/error-message-catalog#3]
I don't know how unification works exactly, so this may be too much to ask. But, say you take this example:

```elm
x = 1
y = "hello"

z = x + y
```

which yields this error message: 

```
-- TYPE MISMATCH -------------------------------------------------------------- 

This expression is triggering a type mismatch.

3| 
4| z = x + y
5|     ^^^^^

To be more specific, as I infer all the types, I am seeing a conflict between
this type:

   number

and this type:

   String
```

which is a great error message. But is it possible to actually tell which of `x` or `y` is the number or the string. Like, say something like:

```
-- TYPE MISMATCH -------------------------------------------------------------- 

This expression is triggering a type mismatch.

3| 
4| z = x + y
5|     ^^^^^

It would seem that you called

(+) : number -> number -> number

with 

x : number

and 

y : String

```

**Comment by evancz** [comment]
I made some tweaks that make it pretty easy to add hints to certain constraints for a relatively low cost. Turns out this was pretty easy to do! Here's the new message:

```
-- TYPE MISMATCH -------------------------------------------------------------- 

The right argument of (+) is causing a type mismatch.

3| 
4|     x + y
5|         ^

To be more specific, as I infer all the types, I am seeing a conflict between
this type:

    number

and this type:

    String

```

**Comment by rtfeldman** [comment]
Is it difficult to provide even more context? I feel like Hassan's example with `y : String` and the type signature of `(+)` was pretty much ideal, but not sure how much harder that is than this.

**Comment by evancz** [comment]
@rtfeldman, that is significantly harder. I am able to give contextual hints about subregions, but I don't have a way to hint about specific types that have been inferred. This would help with normal function application as well. I think this can be a separate issue.

@TheSeamau5, the improvement should be live on the 1234 site.

**Comment by rtfeldman** [comment]
:+1: Makes sense!

**Comment by TheSeamau5** [comment]
Yay! thanks!
