### ISSUE TITLE
When port JS functions throw, Elm reports "notify called synchronously"

### ISSUE THREAD

**Issue by rtfeldman** [evancz/error-message-catalog#31]
To reproduce:

1. Make an outbound port
2. Subscribe to it in JS
3. Have the JS callback that handles the subscription `throw` an exception.

You'll get this error from Elm:

`The notify function has been called synchronously! This can lead to frames being dropped. Definitely report this to <https://github.com/elm-lang/Elm/issues>`

This is confusing because it sounds like there's been some sort of crazy Elm bug...but in reality, it's just a garden variety JS exception.

In an ideal world, Elm would catch the exception and log what port caused it, so it would be easier to track down.

Barring that, it would be nicer to just have a message that didn't lead me down the path of thinking my Elm code was broken (or, worse, that the Elm compiler was broken) when in fact the only issue was that my JS code was broken!

**Comment by rtfeldman** [comment]
Anyone know of a good workaround for this? We've seen over 3,000 of these in production, and can't really debug what the JS problems are because this error message obscures it. :disappointed: 

<img width="1210" alt="screen shot 2015-08-27 at 2 53 38 pm" src="https://cloud.githubusercontent.com/assets/1094080/9534238/db20055a-4ccb-11e5-83fc-46be1be77d16.png">

**Comment by evancz** [comment]
What if you write a version of `subscribe` that does what you want?

```javascript
function safeSubscribe(ports, name, callback) {
    ports[name].subscribe(function(value) {
        try {
            callback(value);
        } catch(e) {
            // rethrow things how you want, mention 'name' so you know who caused it
        }
    });
}
```

Would that cover you until we can do a fix in core?

**Comment by evancz** [comment]
Ah, crap, it cannot rethrow in there. I edited it to work how you need it to!

**Comment by rtfeldman** [comment]
Works! (After one slight modification: `setTimeout` takes the function first and the time second.)

**Comment by evancz** [comment]
Cool, glad we could sort it out temporarily :)

Also, I think `setTimeout` is wrong about that :P

I think this would be better as a bug report on elm-lang/core. I suspect we can do a fix similar to this, though maybe there is something nicer. Should be a tiny change [here](https://github.com/elm-lang/core/blob/2df1163d35841459f51c4176d0ad5631901b2583/src/Native/Port.js#L91-L94) though! Can you migrate this and point to that code snippet?

**Comment by rtfeldman** [comment]
Totally agree on `setTimeout` having the wrong API.

Opened https://github.com/elm-lang/core/issues/374 in `core`.

**Comment by evancz** [comment]
Thanks!
